### ISSUE TITLE
hot reloading doesn't appear to work with the example

### ISSUE THREAD

**Issue by babsonmatt** [gaearon/redux#117]
Following the directions:

```
git clone https://github.com/gaearon/redux.git redux
cd redux
npm install
npm start
```
The example app loads/works fine, but changes to the example files don't seem to cause a hot reload.

Can anyone else confirm this?

Thanks!

**Comment by frankychung** [comment]
@babsonmatt I just tried here and it works for me. Here are the steps I took:

1. Followed your first four commands
2. Went to `http://localhost:3000` and clicked the + button. Count showed 1
3. Edited `examples/stores/counter.js`'s `INCREMENT_COUNTER` case to `return state + 10;` and saved. Clicked + button. Count showed 11

Your console should show something like the following after saving:
```
[WDS] App hot update...
[HMR] Checking for updates on the server...
[HMR] Updated modules:
[HMR]  - 347
[HMR]  - 346
[HMR]  - 226
[HMR] App is up to date.
```

With that are you able to get it to work or do you see a different behavior from what I've described?

**Comment by emmenko** [comment]
It works for me too.
I close this for now since it doesn't appear to be a problem.

@babsonmatt what exactly doesn't work for you? Can you list the steps you do, or what you expect to see?

**Comment by vjpr** [comment]
For anyone with the same problem, I had a similar issue from a project based off the example (a migration from Flummox).

This issue was I was creating my stores outside of a component.

From [react-hot-loader docs - The following modules couldn't be hot updated: (They would need a full reload!)](https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#the-following-modules-couldnt-be-hot-updated-they-would-need-a-full-reload):
 
>This warning may also appear if you edit some non-component file which is required from files other than components. This means hot update bubbled up, but the app couldn't handle it. This is normal! Just refresh.

**Comment by gaearon** [comment]
Oh, this makes sense.

>This issue was I was creating my stores outside of a component. Create a root component, and create stores inside the file that defines the root component.

Not strictly inside that file—it's enough that the `import` chain ends at a React component.
So the important part is: **`import` your stores in `App.js` (root component), not `index.js`**.

@acdlite Might be worth adding into new docs.

**Comment by zuk** [comment]
Maybe this advice is out of date, but I can't make sense of it. In https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/client.js you're creating your store outside of your root component. Does this mean that hot reloading won't work in the react-redux-universal-hot-example?

Is there an example somewhere of how to use `<Provider>` correctly together with hot reloading? Only way I can think of doing this is to make sure that your top level component (`<App />`) is a component rather than a container, since there doesn't seem to be a way to use <Provider> inside a `connect()ed` component....

**Comment by sompylasar** [comment]
@zuk The store itself does not get updated during hot reloading. This allows to keep state while hot-updating the logic -- the reducer.
