### ISSUE TITLE
Allow configuration of Connector's prop-diffing algorithm

### ISSUE THREAD

**Issue by ide** [gaearon/redux#123]
Right now Connector does a shallow comparison of its old and new props in `shouldComponentUpdate` but this isn't guaranteed to be correct if the props are mutable objects. Since the Connector's props aren't managed by Redux it might be right to let the user specify the prop differ or perhaps their own implementation of `shouldComponentUpdate` that gets composed with the default one.

**Comment by gaearon** [comment]
>Right now Connector does a shallow comparison of its old and new props in shouldComponentUpdate but this isn't guaranteed to be correct if the props are mutable objects. 

Yeah but Connector doesn't support any user-specified props right? It only “supports” `children` and `select`.

On the other hand, `@connect` decorator has a [different `shouldComponentUpdate`](https://github.com/gaearon/redux/blob/86ddf8f05147831470cb134542fd8e25c2e12cdb/src/components/createConnectDecorator.js#L12-L14) that bails out if any of the props passed to it are objects. This is because component returned by `@connect` decorator *does* accept (and proxy) user's props.

So I don't believe this is an issue. Please reopen if I missed something.
