### ISSUE TITLE
Initial data loading and reacting to server notifications

### ISSUE THREAD

**Issue by gyzerok** [gaearon/redux#231]
As I've understood for now there is no way to call dispatch from outside of view or action creator.
So I'm not quiet understand how should I deal with initial data loading and in case when server emits an event and I have to call action from API.

**Comment by gyzerok** [comment]
Btw I'm using 0.12 version for now.

**Comment by gaearon** [comment]
>As I've understood for now there is no way to call dispatch from outside of view or action creator.

There is. You get a Redux instance (renamed to Store in 1.0) by calling `createRedux`:

```js
let redux = createRedux(...);
```

It has a `dispatch` method.

See https://github.com/gaearon/redux#running-the-same-code-on-client-and-server

**Comment by gyzerok** [comment]
@gaearon Dont you think that its some kind of boilerplate? Why would we always call actions like dispatch(action())? It there any reasonable way when we need to call action() without dispatch?

**Comment by acdlite** [comment]
@gyzerok I'm wondering, what does the non-boilerplate version of that look like to you? `dispatch()` just takes an action object. If you don't what to use action creators, that's up to you.

**Comment by gyzerok** [comment]
@acdlite mb I did no get it right.. I'm taking about calling actions like ```action()``` from anywhere. Like we do after bindActionCreators in the view. For now if I have to call an action from my API wrapper I need to do: move redux creation into a separate file, import dispatch, import action. And my point of view is: why do we need 2 function in place of one if we always have to "call them together"?

**Comment by acdlite** [comment]
@gyzerok Again, do you have a better alternative in mind?

**Comment by gyzerok** [comment]
@acdlite making action execution simple by calling ```someAction()``` without dispatch?

**Comment by acdlite** [comment]
Where does `someAction()` come from? How to you access it?

**Comment by gyzerok** [comment]
@acdlite Lets hold on a little. Do we need to talk about concrete solution before we agree that it would be better?

**Comment by acdlite** [comment]
@gyzerok I'm trying to prove a point :) If you can come up with a concrete solution that's less boilerplate than the current solution, then we can consider it. I don't think one exists, but I'd be happy to be proven wrong.

One solution is to bind just once after creating your store, then exporting the bound action creators as a singleton. But this doesn't work for server-side rendering — you need to pass dispatch through the React component tree using context, like we do with state subscriptions. If you don't care about server-side rendering, though, then a singleton is fine.

Another solution is to update the Connector API so that instead of passing `dispatch()`, it passes a collection of bound action creators. But then that means you have to register them somehow with the Store upon creation. And then, in the Connector, you need an API to select just the ones you want. To me, this is a lot more boilerplate than just a single function call, `bindActionCreators()` at the Connector site.

Again, though, I'd be happy to be proven wrong!

**Comment by gyzerok** [comment]
The best point here I suppose is to decorate action creators with dispatch, but for now we cant use decorators on an exported function.

Thank you for your explanation though!

**Comment by acdlite** [comment]
Even if you could use a decorator...

```js
@bindActionCreator(dispatch)
export actionCreator() {}
```

where does `dispatch()` come from?

**Comment by gyzerok** [comment]
@acdlite in this way I can import it from redux instance like I do now.

**Comment by acdlite** [comment]
@gyzerok That requires creating a singleton. Not the worst thing ever, just be aware of the downsides.

**Comment by gyzerok** [comment]
As I understand for now there is no way to handle with my problem without creating singleton.
Is there another way to perform action on some event from the server?

**Comment by acdlite** [comment]
Pass the store to a function

```js
function listenToServer(store) {
  // ...
  store.dispatch()
}
```

then call that function from wherever you call `createStore()`.

**Comment by gyzerok** [comment]
@acdlite do you mean redux instance by the store? If so I do not see any differences from importing dispatch from this instance and calling it as ```dispatch(actionCreator())```. Correct me if I'm wrong.

**Comment by acdlite** [comment]
@gyzerok The Redux instance is being renamed to Store in 1.0, sorry for the confusion.https://github.com/gaearon/redux/pull/195

And you're right, just passing dispatch would be even better.
