### ISSUE TITLE
Higher order store ideas

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux#264]
Higher order stores are a new powerful extension mechanism for Redux. It's more powerful than middleware so you should only use it if you need something the middleware can't do:

* transform the state
* ignore some actions
* introduce asynchrony
* fire some actions “out of the blue”

There is some work in progress on higher-order store docs. [This doc](https://github.com/gaearon/redux/blob/cdaa3e81ffdf49e25ce39eeed37affc8f0c590f7/docs/higher-order-stores.md) should introduce you to the idea.

I created this issue to discuss potential applications of higher order stores.
These are what I have in mind:

* Time travel (#113) in Redux DevTools (already implemented)
* Persisting state in development across reloads (already implemented)
* Offloading some work to a webworker, maybe? #263 
* Record and replay serialized user sessions
* Remote sync (Flux over the wire #211 for debugging user sessions?)

Anything else?

**Comment by gaearon** [comment]
cc @elierotenberg in case he'd like to experiment with using HOS to implement Redux over the Wire

**Comment by nbostrom** [comment]
I'm playing around with something similar using scuttlebutt (https://www.npmjs.com/package/scuttlebutt) because of its ecosystem like integrations with localstorage and leveldb. I'm calling it "redux-gossip". I was using a custom thunk for this, which gave me some problems. A higher order store is definitely the way to go. Thanks for this!

**Comment by gaearon** [comment]
I'm closing this as too generic.
Let's discuss “Redux over the Wire” and related ideas in #313.
