### ISSUE TITLE
how to use the Store.auth on .onEnter of React-router

### ISSUE THREAD

**Issue by devalphac** [gaearon/redux#283]
Can you give me some advice. Thank you very much
```
export default class Home extends React.Component {
...
}

Home.onEnter = function(next, transition) {
    if(!store.auth) {
         // transition.to('/sigin');
    }
}
```

**Comment by emmenko** [comment]
This might help https://github.com/emmenko/redux-react-router-async-example/blob/router-login/lib/Root.js#L57-L62

**Comment by devalphac** [comment]
thanks @emmenko

**Comment by emmenko** [comment]
:+1:

**Comment by jljorgenson18** [comment]
So that link is dead. Any chance on anyone having an updated link or an example? I'm trying to dispatch an action to sync the "active user" (whoever is logged in at that moment), listen for a single update after the action is dispatch, then unsubscribe once I get the response. I tried making the initial store object accessible in a separate module and then referencing that object but this led to unexpected store updates. Any help would be greatly appreciated!

**Comment by gaearon** [comment]
@jljorgenson18

Please ask this on StackOverflow.
It's a better place for such questions.

**Comment by pjvds** [comment]
Just to be helpful, here is the new link location:

https://github.com/emmenko/redux-react-router-async-example/blob/8811bcbc0eafabff50823bb1f5ef171fdd2bc782/lib/Root.js#L68
