### ISSUE TITLE
How to handle 1-to-many reducers?

### ISSUE THREAD

**Issue by Keats** [gaearon/redux#327]
I asked this question in the flux channel but we found out that not enough people used flux at scale to have a good answer.
Let's take Trello as an example: you have several columns with several cards.

The answer was to have a Columns reducer that contains data (name, date etc) with a cards array containing id references to data stored in a Cards reducer (which would be basically a dict with the object id as keys).
It looks ok as a concept but how do you handle optimistic update such as creating a card and having it displayed before the request finishes as you won't have the id yet for example.  

I'm sure there are other things I didn't think of, that's only the first con that popped in my head.

Anyone having experiences with stores/reducers and how they organize them?

**Comment by gaearon** [comment]
This is not really specific to Redux, so I'd suggest creating a StackOverflow question.

**Comment by gaearon** [comment]
(I'm not saying the question is bad or invalid. It is in fact very good. It's just that it's better suited for a general purpose forum or discussion board because it equally applies to Redux and Flux, and there are many possible solutions depending on what kind of user experience you're aiming for. If you _do_ create a question on StackOverflow, please link it from here, and I'll try my best to answer it.)

**Comment by Keats** [comment]
Yeah it didn't really fit that well but i believe it should be part of the example/docs eventually since it's probably one of the most common usecase in flux.

Here's the stackoverflow question http://stackoverflow.com/questions/31641466/how-to-handle-1-to-many-relationships-in-flux-stores
