### ISSUE TITLE
Rename Actions to "Records"?

### ISSUE THREAD

**Issue by wmertens** [gaearon/redux#377]
I love the rename of Stores to Reducers, it really changes how you think about the code, and I noticed that there is some confusion between actual actions taken and the record of their results as Action objects.

Action objects are really only news items and they can be recorded by the reducers but they don't perform any work, that was already done. (started a request, got data from server etc).

Therefore I think it would help our mental model if they are renamed to  Records (or NewsItems, Events, ...?).

Then ActionCreators can remain the "actions" they are colloquially (or even be renamed to just Actions).

It would look like this:

![redux flow](https://cloud.githubusercontent.com/assets/54934/9002329/ceaa7004-3762-11e5-886d-ab5fb604c3f8.png)

**Comment by gaearon** [comment]
We've been bikeshedding on this for quite a while, and from the conversations I was in, I didn't find any better word than “actions”. A new term has to be *significantly* better to justify inventing yet another terminology.

Redux names comes from “Flux with reducers” and it makes sense for me to keep the Flux terminology, at least to aid the beginners.

In the new docs, we are calling them “actions” and “async actions”. I tried calling them “intents” but that just complicates docs because there is clearly a new term, but their role in Redux is supplementary rather than critical.

**Comment by wmertens** [comment]
Another good name I heard was Fact. Just recording for posterity.

**Comment by adri** [comment]
Events is a common term for facts in the event sourcing world.

**Comment by edge** [comment]
What about `Memo`? Since that's what actions really kind of are. Just like in real life, Memos are read and acted upon by the Reducers (workers), and may be intercepted or modified on the way by Middleware (higher-ups).

Additionally, I think `Record` might be really confusing for Immutable users.
