### ISSUE TITLE
bindActionCreators should provide a better error

### ISSUE THREAD

**Issue by jarsbe** [gaearon/redux#407]
Often I do this:

`import MyActions from '../actions/MyActions';`

And when I try to bind actions `{...bindActionCreators(MyActions, dispatch)}` I get an error from `mapValues.js`:`Cannot convert undefined or null to object`.

This is because my import should be:

`import * as MyActions from '../actions/MyActions';`

It would be nice if the error informed me that `MyActions` is undefined since I seem to do this ALL the time.

**Comment by gaearon** [comment]
I'd accept a PR (to `breaking-changes-1.0` branch) that verifies that, if the argument isn't a function, then at least it's `!= null`.

We could change the error message to `bindActionCreators expected an object or a function, instead received %s. Did you write "import ActionCreators from" instead of "import * as ActionCreators from"?`

**Comment by jarsbe** [comment]
Great, I'd be more than happy to.

**Comment by gaearon** [comment]
Fixed by #411.
