### ISSUE TITLE
Unsubscribe a listener inside a listener has side-effects on other listeners

### ISSUE THREAD

**Issue by arian** [gaearon/redux#461]
Unsubscribing a listener inside a listener, will splice the `listeners` array in the store of `createStore`, while looping over that array using `forEach` in `dispatch`.

For example the following program fails:

```js
import assert from 'assert';
import {createStore} from 'redux';

var store = createStore(() => []);

var countA = 0;
var countB = 0;
var countC = 0;

var unsubA = store.subscribe(() => {
	countA++;
});

var unsubB = store.subscribe(() => {
	countB++;
	unsubB();
});

var unsubC = store.subscribe(() => {
	countC++;
});

store.dispatch({type: 'X'});
store.dispatch({type: 'Y'});

console.log(countA, countB, countC);

assert.equal(countA, 2, 'countA');
assert.equal(countB, 1, 'countB');
assert.equal(countC, 2, 'countC');
```

`countC` is **1**, but it should be **2**.

A fix for this problem would be to copy the array before doing the `forEach` in the `dispatch` function, for example:

```js
listeners.slice().forEach(listener => listener());
```

**Comment by gaearon** [comment]
Thanks! Would you please add a failing test? (And maybe you'd like to contribute a fix too? ;-)
The branch for development is `breaking-changes-1.0`.

**Comment by gaearon** [comment]
Fixed by #462.

**Comment by xogeny** [comment]
I have a question about this.  The idea is the copy the array so subscribes can't affect the loop.  But if the first listener unsubscribes a later listener, that won't be handled correctly.  The unsubscribed listener will be called one more time *after* it was unsubscribed.

Is that really the desired behavior?  I agree it is a tricky issue and I'm not 100% certain how to address that.  But before even trying to create a PR I wanted to take a step back and ask the "big picture" question of "When do we expect an unsubscribe to be applied?".  Specifically, how should this case where one listener unsubscribes a later listener? (one of many potential corner cases worth considering)

Although not strictly relevant, I think it might be worth nothing that this is an issue with React because you can get into a situation (this is how I got here, in fact) where a component gets unsubscribed when it is unmounted.  But the listener is invoke on more time after the unsubscribe/unmounting and the listener calls `setState` which leads to a nasty message on the console.  I'm trying to avoid that situation.  In my case, I want the unsubscribe to be effective immediately because otherwise the listener will be called after the component is unmounted.

Thoughts?

**Comment by itbrandonsilva** [comment]
#2132
